export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ApiPayloadField {
  name: string;
  type: string;
  required: boolean;
}

export interface ApiEndpointDoc {
  id: string;
  title: string;
  method: HttpMethod;
  endpoint: string;
  payload: ApiPayloadField[];
  successExample: string;
  errorExample: string;
}

export interface ApiDocGroup {
  key: string;
  titleKey: string;
  endpoints: ApiEndpointDoc[];
}

export const API_DOC_GROUPS: ApiDocGroup[] = [
  {
    key: "auth",
    titleKey: "apiDoc.groups.auth",
    endpoints: [
      {
        id: "register",
        title: "Register",
        method: "POST",
        endpoint: "/auth/register",
        payload: [
          { name: "nameUser", type: "string", required: true },
          { name: "username", type: "string", required: true },
          { name: "password", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Registrasi berhasil, menunggu validasi admin",
            data: {
              idUser: "2",
              nameUser: "Jane Doe",
              username: "janedoe",
              role: "user",
              status: "pending",
              createdAt: "2026-07-13T08:30:00.000Z",
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Username sudah terdaftar",
            data: { error: "Username sudah terdaftar" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "login",
        title: "Login",
        method: "POST",
        endpoint: "/auth/login",
        payload: [
          { name: "username", type: "string", required: true },
          { name: "password", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Login berhasil",
            data: {
              token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
              user: {
                idUser: "1",
                nameUser: "John Doe",
                username: "johndoe",
                role: "admin",
                status: "active",
                createdAt: "2026-01-05T02:15:00.000Z",
              },
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Username atau password salah",
            data: { error: "Username atau password salah" },
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
      {
        id: "get-user",
        title: "Get User",
        method: "GET",
        endpoint: "/user/me",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil data user",
            data: {
              idUser: "1",
              nameUser: "John Doe",
              username: "johndoe",
              role: "admin",
              status: "active",
              createdAt: "2026-01-05T02:15:00.000Z",
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Menunggu validasi",
            data: {},
            isSuccess: false,
            status: 403,
          },
          null,
          2,
        ),
      },
      {
        id: "update-profile",
        title: "Update Profile",
        method: "PATCH",
        endpoint: "/user/me",
        payload: [
          { name: "nameUser", type: "string", required: true },
          { name: "username", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Profil berhasil diperbarui",
            data: {
              idUser: "1",
              nameUser: "John Doe Updated",
              username: "johndoe2",
              role: "admin",
              status: "active",
              createdAt: "2026-01-05T02:15:00.000Z",
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Username sudah digunakan",
            data: { error: "Username sudah digunakan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "change-password",
        title: "Change Password",
        method: "PATCH",
        endpoint: "/user/me/password",
        payload: [
          { name: "currentPassword", type: "string", required: true },
          { name: "newPassword", type: "string (min. 6 characters)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Password berhasil diubah, silakan login kembali",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Password lama salah",
            data: { error: "Password lama salah" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "get-list-user",
        title: "Get List User",
        method: "GET",
        endpoint: "/user/get-list-user",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar user",
            data: [
              {
                idUser: "1",
                nameUser: "John Doe",
                username: "johndoe",
                role: "admin",
                status: "active",
                createdAt: "2026-01-05T02:15:00.000Z",
              },
              {
                idUser: "2",
                nameUser: "Jane Doe",
                username: "janedoe",
                role: "user",
                status: "pending",
                createdAt: "2026-07-13T08:30:00.000Z",
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Forbidden: admin only",
            data: {},
            isSuccess: false,
            status: 403,
          },
          null,
          2,
        ),
      },
      {
        id: "accept-user",
        title: "Accept User",
        method: "POST",
        endpoint: "/user/accept-user",
        payload: [{ name: "idUser", type: "string", required: true }],
        successExample: JSON.stringify(
          {
            message: "User berhasil divalidasi",
            data: {
              idUser: "2",
              nameUser: "Jane Doe",
              username: "janedoe",
              role: "user",
              status: "active",
              createdAt: "2026-07-13T08:30:00.000Z",
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "User tidak ditemukan",
            data: { error: "User tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "logout",
        title: "Logout",
        method: "POST",
        endpoint: "/auth/logout",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Logout berhasil",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Invalid or expired token",
            data: {},
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "wallet",
    titleKey: "apiDoc.groups.wallet",
    endpoints: [
      {
        id: "list-wallets",
        title: "List Wallets",
        method: "GET",
        endpoint: "/wallets",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar wallet",
            data: [
              {
                idWallet: "6a54775fb2c4f567c96e74f4",
                nameWallet: "Cash",
                color: "#a16207",
                balance: 850000,
                transactionCount: 42,
                isPrimary: true,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Unauthorized",
            data: {},
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
      {
        id: "create-wallet",
        title: "Create Wallet",
        method: "POST",
        endpoint: "/wallets",
        payload: [
          { name: "nameWallet", type: "string", required: true },
          { name: "color", type: "string", required: true },
          { name: "balance", type: "number", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Wallet berhasil dibuat",
            data: {
              idWallet: "6a54775fb2c4f567c96e74f6",
              nameWallet: "Dana Liburan",
              color: "#075985",
              balance: 0,
              transactionCount: 0,
              isPrimary: false,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "nameWallet dan color wajib diisi",
            data: { error: "nameWallet dan color wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-wallet",
        title: "Update Wallet",
        method: "PATCH",
        endpoint: "/wallets/:idWallet",
        payload: [
          { name: "nameWallet", type: "string", required: true },
          { name: "color", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Wallet berhasil diperbarui",
            data: {
              idWallet: "6a54775fb2c4f567c96e74f6",
              nameWallet: "Dana Liburan 2027",
              color: "#3f6212",
              balance: 0,
              transactionCount: 0,
              isPrimary: false,
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Wallet tidak ditemukan",
            data: { error: "Wallet tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-wallet",
        title: "Delete Wallet",
        method: "DELETE",
        endpoint: "/wallets/:idWallet",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Wallet berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Wallet tidak ditemukan",
            data: { error: "Wallet tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "set-primary-wallet",
        title: "Set Primary Wallet",
        method: "PATCH",
        endpoint: "/wallets/:idWallet/primary",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Wallet utama berhasil diubah",
            data: [
              {
                idWallet: "6a54775fb2c4f567c96e74f4",
                nameWallet: "Cash",
                color: "#a16207",
                balance: 850000,
                transactionCount: 42,
                isPrimary: false,
              },
              {
                idWallet: "6a54775fb2c4f567c96e74f6",
                nameWallet: "Dana Liburan",
                color: "#075985",
                balance: 0,
                transactionCount: 0,
                isPrimary: true,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Wallet tidak ditemukan",
            data: { error: "Wallet tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "reorder-wallets",
        title: "Reorder Wallets",
        method: "PATCH",
        endpoint: "/wallets/reorder",
        payload: [{ name: "orderedIds", type: "string[]", required: true }],
        successExample: JSON.stringify(
          {
            message: "Urutan wallet berhasil disimpan",
            data: [
              {
                idWallet: "6a54775fb2c4f567c96e74f6",
                nameWallet: "Dana Liburan",
                color: "#075985",
                balance: 0,
                transactionCount: 0,
                isPrimary: true,
              },
              {
                idWallet: "6a54775fb2c4f567c96e74f4",
                nameWallet: "Cash",
                color: "#a16207",
                balance: 850000,
                transactionCount: 42,
                isPrimary: false,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "orderedIds wajib diisi",
            data: { error: "orderedIds wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "category",
    titleKey: "apiDoc.groups.category",
    endpoints: [
      {
        id: "list-categories",
        title: "List Categories",
        method: "GET",
        endpoint: "/categories",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar kategori",
            data: [
              {
                idCategory: "6a54caaa84245dacc470c8c1",
                nameCategory: "Makan",
                type: "expense",
                color: "#E2574C",
                icon: "HiOutlineCake",
                transactionCount: 12,
                subCategories: [
                  {
                    idSubCategory: "6a54cab784245dacc470c8ca",
                    idCategory: "6a54caaa84245dacc470c8c1",
                    nameSubCategory: "Warteg",
                    icon: "HiOutlineBuildingStorefront",
                    transactionCount: 5,
                  },
                ],
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Unauthorized",
            data: {},
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
      {
        id: "create-category",
        title: "Create Category",
        method: "POST",
        endpoint: "/categories",
        payload: [
          { name: "nameCategory", type: "string", required: true },
          { name: "type", type: '"income" | "expense"', required: true },
          { name: "color", type: "string", required: true },
          { name: "icon", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Kategori berhasil dibuat",
            data: {
              idCategory: "6a54cab784245dacc470c8c6",
              nameCategory: "Gaji",
              type: "income",
              color: "#7CB87C",
              icon: "HiOutlineBriefcase",
              transactionCount: 0,
              subCategories: [],
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "nameCategory, type, color, dan icon wajib diisi",
            data: { error: "nameCategory, type, color, dan icon wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-category",
        title: "Update Category",
        method: "PATCH",
        endpoint: "/categories/:idCategory",
        payload: [
          { name: "nameCategory", type: "string", required: true },
          { name: "type", type: '"income" | "expense"', required: true },
          { name: "color", type: "string", required: true },
          { name: "icon", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Kategori berhasil diperbarui",
            data: {
              idCategory: "6a54cab784245dacc470c8c6",
              nameCategory: "Gaji Bulanan",
              type: "income",
              color: "#075985",
              icon: "HiOutlineBanknotes",
              transactionCount: 0,
              subCategories: [],
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Kategori tidak ditemukan",
            data: { error: "Kategori tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-category",
        title: "Delete Category",
        method: "DELETE",
        endpoint: "/categories/:idCategory",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Kategori berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Kategori tidak ditemukan",
            data: { error: "Kategori tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "reorder-categories",
        title: "Reorder Categories",
        method: "PATCH",
        endpoint: "/categories/reorder",
        payload: [{ name: "orderedIds", type: "string[]", required: true }],
        successExample: JSON.stringify(
          {
            message: "Urutan kategori berhasil disimpan",
            data: [
              {
                idCategory: "6a54cab784245dacc470c8c6",
                nameCategory: "Gaji",
                type: "income",
                color: "#7CB87C",
                icon: "HiOutlineBriefcase",
                transactionCount: 0,
                subCategories: [],
              },
              {
                idCategory: "6a54caaa84245dacc470c8c1",
                nameCategory: "Makan",
                type: "expense",
                color: "#E2574C",
                icon: "HiOutlineCake",
                transactionCount: 12,
                subCategories: [],
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "orderedIds wajib diisi",
            data: { error: "orderedIds wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "create-subcategory",
        title: "Create Subcategory",
        method: "POST",
        endpoint: "/categories/:idCategory/subcategories",
        payload: [
          { name: "nameSubCategory", type: "string", required: true },
          { name: "icon", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Subkategori berhasil dibuat",
            data: {
              idSubCategory: "6a54cab784245dacc470c8cf",
              idCategory: "6a54caaa84245dacc470c8c1",
              nameSubCategory: "Restoran",
              icon: "HiOutlineBuildingStorefront",
              transactionCount: 0,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "nameSubCategory dan icon wajib diisi",
            data: { error: "nameSubCategory dan icon wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-subcategory",
        title: "Update Subcategory",
        method: "PATCH",
        endpoint: "/categories/:idCategory/subcategories/:idSubCategory",
        payload: [
          { name: "nameSubCategory", type: "string", required: true },
          { name: "icon", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Subkategori berhasil diperbarui",
            data: {
              idSubCategory: "6a54cab784245dacc470c8cf",
              idCategory: "6a54caaa84245dacc470c8c1",
              nameSubCategory: "Restoran Padang",
              icon: "HiOutlineBuildingStorefront",
              transactionCount: 0,
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Subkategori tidak ditemukan",
            data: { error: "Subkategori tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-subcategory",
        title: "Delete Subcategory",
        method: "DELETE",
        endpoint: "/categories/:idCategory/subcategories/:idSubCategory",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Subkategori berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Subkategori tidak ditemukan",
            data: { error: "Subkategori tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "reorder-subcategories",
        title: "Reorder Subcategories",
        method: "PATCH",
        endpoint: "/categories/:idCategory/subcategories/reorder",
        payload: [{ name: "orderedIds", type: "string[]", required: true }],
        successExample: JSON.stringify(
          {
            message: "Urutan subkategori berhasil disimpan",
            data: [
              {
                idSubCategory: "6a54cab784245dacc470c8cf",
                idCategory: "6a54caaa84245dacc470c8c1",
                nameSubCategory: "Kopi",
                icon: "HiOutlineCake",
                transactionCount: 0,
              },
              {
                idSubCategory: "6a54cab784245dacc470c8ca",
                idCategory: "6a54caaa84245dacc470c8c1",
                nameSubCategory: "Warteg",
                icon: "HiOutlineBuildingStorefront",
                transactionCount: 5,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "orderedIds wajib diisi",
            data: { error: "orderedIds wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "transaction",
    titleKey: "apiDoc.groups.transaction",
    endpoints: [
      {
        id: "list-transactions",
        title: "List Transactions",
        method: "GET",
        endpoint: "/transactions?month=2026-07&type=expense&idWallet=wallet-1&idCategory=category-1&idSubCategory=subcategory-1&dateFrom=2026-07-01&dateTo=2026-07-15&search=makan&sort=dateDesc&page=1&limit=20",
        payload: [
          { name: "month", type: "string (YYYY-MM)", required: false },
          { name: "type", type: '"income" | "expense" | "transfer" | "correction"', required: false },
          { name: "idWallet", type: "string", required: false },
          { name: "idCategory", type: "string", required: false },
          { name: "idSubCategory", type: "string", required: false },
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: false },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: false },
          { name: "search", type: "string", required: false },
          {
            name: "sort",
            type: '"dateDesc" | "dateAsc" | "amountDesc" | "amountAsc"',
            required: false,
          },
          { name: "page", type: "number (omit with limit for the full unpaginated result)", required: false },
          { name: "limit", type: "number", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar transaksi",
            isSuccess: true,
            status: 200,
            data: {
              transactions: [
                {
                  idTransaction: "transaction-1",
                  type: "expense",
                  idWallet: "wallet-1",
                  idCategory: "category-1",
                  idSubCategory: "subcategory-1",
                  idWalletFrom: null,
                  idWalletTo: null,
                  title: "Warteg nasi, ayam, toge",
                  notes: "",
                  amount: 17000,
                  date: "2026-07-10T09:34:00.000Z",
                },
                {
                  idTransaction: "transaction-2",
                  type: "transfer",
                  idWallet: null,
                  idCategory: null,
                  idSubCategory: null,
                  idWalletFrom: "wallet-2",
                  idWalletTo: "wallet-1",
                  title: "Jago Transfer Out → Cash Transfer In",
                  notes: "",
                  amount: 100000,
                  date: "2026-06-28T08:00:00.000Z",
                },
                {
                  idTransaction: "transaction-3",
                  type: "correction",
                  idWallet: "wallet-1",
                  idCategory: null,
                  idSubCategory: null,
                  idWalletFrom: null,
                  idWalletTo: null,
                  title: "Balance Correction",
                  notes: "Penyesuaian saldo aktual",
                  amount: 3000,
                  date: "2026-06-25T07:00:00.000Z",
                },
              ],
              total: 3,
              page: 1,
              limit: 20,
              totalPages: 1,
              summary: {
                income: 0,
                expense: 20000,
                net: -20000,
                categoryBreakdown: [
                  {
                    idCategory: "category-1",
                    nameCategory: "Makan",
                    color: "#E2574C",
                    icon: "IoFastFoodOutline",
                    amount: 17000,
                    transactionCount: 1,
                    percentage: 85,
                    subCategoryBreakdown: [
                      {
                        idSubCategory: "subcategory-1",
                        nameSubCategory: "Warteg",
                        icon: "MdOutlineRestaurant",
                        amount: 17000,
                        transactionCount: 1,
                        percentage: 100,
                      },
                    ],
                  },
                ],
              },
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token sudah tidak berlaku, silakan login kembali",
            isSuccess: false,
            status: 401,
            data: { error: "Token sudah tidak berlaku, silakan login kembali" },
          },
          null,
          2,
        ),
      },
      {
        id: "create-transaction",
        title: "Create Transaction",
        method: "POST",
        endpoint: "/transactions",
        payload: [
          { name: "type", type: '"income" | "expense" | "transfer" | "correction"', required: true },
          { name: "idWallet", type: "string | null", required: false },
          { name: "idCategory", type: "string | null", required: false },
          { name: "idSubCategory", type: "string | null", required: false },
          { name: "idWalletFrom", type: "string | null", required: false },
          { name: "idWalletTo", type: "string | null", required: false },
          { name: "title", type: "string", required: true },
          { name: "notes", type: "string", required: false },
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string (ISO 8601)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Transaksi berhasil dibuat",
            isSuccess: true,
            status: 201,
            data: {
              idTransaction: "transaction-4",
              type: "expense",
              idWallet: "wallet-1",
              idCategory: "category-1",
              idSubCategory: "subcategory-1",
              idWalletFrom: null,
              idWalletTo: null,
              title: "Ngasih",
              notes: "",
              amount: 100000,
              date: "2026-07-10T10:00:00.000Z",
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Kategori tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Kategori tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "update-transaction",
        title: "Update Transaction",
        method: "PATCH",
        endpoint: "/transactions/:idTransaction",
        payload: [
          { name: "type", type: '"income" | "expense" | "transfer" | "correction"', required: true },
          { name: "idWallet", type: "string | null", required: false },
          { name: "idCategory", type: "string | null", required: false },
          { name: "idSubCategory", type: "string | null", required: false },
          { name: "idWalletFrom", type: "string | null", required: false },
          { name: "idWalletTo", type: "string | null", required: false },
          { name: "title", type: "string", required: true },
          { name: "notes", type: "string", required: false },
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string (ISO 8601)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Transaksi berhasil diperbarui",
            isSuccess: true,
            status: 200,
            data: {
              idTransaction: "transaction-4",
              type: "expense",
              idWallet: "wallet-1",
              idCategory: "category-1",
              idSubCategory: "subcategory-1",
              idWalletFrom: null,
              idWalletTo: null,
              title: "Ngasih ke adek",
              notes: "",
              amount: 150000,
              date: "2026-07-10T10:00:00.000Z",
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Transaksi tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Transaksi tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "delete-transaction",
        title: "Delete Transaction",
        method: "DELETE",
        endpoint: "/transactions/:idTransaction",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Transaksi berhasil dihapus",
            isSuccess: true,
            status: 200,
            data: {},
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Transaksi tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Transaksi tidak ditemukan" },
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "schedule",
    titleKey: "apiDoc.groups.schedule",
    endpoints: [
      {
        id: "list-schedules",
        title: "List Schedules",
        method: "GET",
        endpoint: "/schedules",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar jadwal",
            isSuccess: true,
            status: 200,
            data: [
              {
                idSchedule: "schedule-1",
                title: "Gaji Bulanan",
                notes: "",
                type: "income",
                amount: 8000000,
                idWallet: "wallet-1",
                idCategory: "category-2",
                idSubCategory: null,
                frequency: "monthly",
                weekdays: [],
                dayOfMonth: 1,
                month: null,
                startDate: "2026-08-01T00:00:00.000Z",
                isActive: true,
              },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token sudah tidak berlaku, silakan login kembali",
            isSuccess: false,
            status: 401,
            data: { error: "Token sudah tidak berlaku, silakan login kembali" },
          },
          null,
          2,
        ),
      },
      {
        id: "create-schedule",
        title: "Create Schedule",
        method: "POST",
        endpoint: "/schedules",
        payload: [
          { name: "title", type: "string", required: true },
          { name: "notes", type: "string", required: false },
          { name: "type", type: '"income" | "expense"', required: true },
          { name: "amount", type: "number", required: true },
          { name: "idWallet", type: "string", required: true },
          { name: "idCategory", type: "string", required: true },
          { name: "idSubCategory", type: "string | null", required: false },
          { name: "frequency", type: '"daily" | "weekly" | "monthly" | "yearly"', required: true },
          {
            name: "weekdays",
            type: "number[] (0=Sun..6=Sat, required when frequency is weekly)",
            required: false,
          },
          { name: "startDate", type: "string (ISO 8601)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Jadwal berhasil dibuat",
            isSuccess: true,
            status: 201,
            data: {
              idSchedule: "schedule-1",
              title: "Gaji Bulanan",
              notes: "",
              type: "income",
              amount: 8000000,
              idWallet: "wallet-1",
              idCategory: "category-2",
              idSubCategory: null,
              frequency: "monthly",
              weekdays: [],
              dayOfMonth: 1,
              month: null,
              startDate: "2026-08-01T00:00:00.000Z",
              isActive: true,
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Kategori tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Kategori tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "update-schedule",
        title: "Update Schedule",
        method: "PATCH",
        endpoint: "/schedules/:idSchedule",
        payload: [
          { name: "title", type: "string", required: true },
          { name: "notes", type: "string", required: false },
          { name: "type", type: '"income" | "expense"', required: true },
          { name: "amount", type: "number", required: true },
          { name: "idWallet", type: "string", required: true },
          { name: "idCategory", type: "string", required: true },
          { name: "idSubCategory", type: "string | null", required: false },
          { name: "frequency", type: '"daily" | "weekly" | "monthly" | "yearly"', required: true },
          { name: "weekdays", type: "number[] (0=Sun..6=Sat)", required: false },
          { name: "startDate", type: "string (ISO 8601)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Jadwal berhasil diperbarui",
            isSuccess: true,
            status: 200,
            data: {
              idSchedule: "schedule-1",
              title: "Gaji Bulanan",
              notes: "",
              type: "income",
              amount: 8500000,
              idWallet: "wallet-1",
              idCategory: "category-2",
              idSubCategory: null,
              frequency: "monthly",
              weekdays: [],
              dayOfMonth: 1,
              month: null,
              startDate: "2026-08-01T00:00:00.000Z",
              isActive: true,
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Schedule tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Schedule tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "pause-schedule",
        title: "Pause / Resume Schedule",
        method: "PATCH",
        endpoint: "/schedules/:idSchedule/pause",
        payload: [{ name: "isActive", type: "boolean", required: true }],
        successExample: JSON.stringify(
          {
            message: "Jadwal dijeda",
            isSuccess: true,
            status: 200,
            data: {
              idSchedule: "schedule-1",
              title: "Gaji Bulanan",
              notes: "",
              type: "income",
              amount: 8000000,
              idWallet: "wallet-1",
              idCategory: "category-2",
              idSubCategory: null,
              frequency: "monthly",
              weekdays: [],
              dayOfMonth: 1,
              month: null,
              startDate: "2026-08-01T00:00:00.000Z",
              isActive: false,
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Schedule tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Schedule tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "delete-schedule",
        title: "Delete Schedule",
        method: "DELETE",
        endpoint: "/schedules/:idSchedule",
        payload: [],
        successExample: JSON.stringify(
          { message: "Jadwal berhasil dihapus", isSuccess: true, status: 200, data: {} },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Schedule tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Schedule tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "list-schedule-occurrences",
        title: "List Pending Occurrences",
        method: "GET",
        endpoint: "/schedules/occurrences",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar jadwal menunggu",
            isSuccess: true,
            status: 200,
            data: [
              {
                idOccurrence: "occurrence-1",
                idSchedule: "schedule-1",
                dueDate: "2026-08-01T00:00:00.000Z",
                status: "pending",
                type: "income",
                title: "Gaji Bulanan",
                amount: 8000000,
                idWallet: "wallet-1",
                idCategory: "category-2",
                idSubCategory: null,
                idTransaction: null,
              },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token sudah tidak berlaku, silakan login kembali",
            isSuccess: false,
            status: 401,
            data: { error: "Token sudah tidak berlaku, silakan login kembali" },
          },
          null,
          2,
        ),
      },
      {
        id: "pay-schedule-occurrence",
        title: "Pay Occurrence",
        method: "POST",
        endpoint: "/schedules/occurrences/:idOccurrence/pay",
        payload: [
          { name: "amount", type: "number", required: false },
          { name: "date", type: "string (ISO 8601, defaults to now)", required: false },
          { name: "idWallet", type: "string", required: false },
          { name: "idCategory", type: "string", required: false },
          { name: "idSubCategory", type: "string | null", required: false },
          { name: "title", type: "string", required: false },
          { name: "notes", type: "string", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Transaksi berhasil dikonfirmasi",
            isSuccess: true,
            status: 201,
            data: {
              transaction: {
                idTransaction: "transaction-5",
                type: "income",
                idWallet: "wallet-1",
                idCategory: "category-2",
                idSubCategory: null,
                idWalletFrom: null,
                idWalletTo: null,
                title: "Gaji Bulanan",
                notes: "",
                amount: 8000000,
                date: "2026-08-01T09:00:00.000Z",
              },
              occurrence: {
                idOccurrence: "occurrence-1",
                idSchedule: "schedule-1",
                dueDate: "2026-08-01T00:00:00.000Z",
                status: "paid",
                type: "income",
                title: "Gaji Bulanan",
                amount: 8000000,
                idWallet: "wallet-1",
                idCategory: "category-2",
                idSubCategory: null,
                idTransaction: "transaction-5",
              },
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Jadwal sudah diproses atau tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Jadwal sudah diproses atau tidak ditemukan" },
          },
          null,
          2,
        ),
      },
      {
        id: "cancel-schedule-occurrence",
        title: "Cancel Occurrence",
        method: "POST",
        endpoint: "/schedules/occurrences/:idOccurrence/cancel",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Jadwal dibatalkan",
            isSuccess: true,
            status: 200,
            data: {
              idOccurrence: "occurrence-1",
              idSchedule: "schedule-1",
              dueDate: "2026-08-01T00:00:00.000Z",
              status: "cancelled",
              type: "income",
              title: "Gaji Bulanan",
              amount: 8000000,
              idWallet: "wallet-1",
              idCategory: "category-2",
              idSubCategory: null,
              idTransaction: null,
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Jadwal sudah diproses atau tidak ditemukan",
            isSuccess: false,
            status: 400,
            data: { error: "Jadwal sudah diproses atau tidak ditemukan" },
          },
          null,
          2,
        ),
      },
    ],
  },
  // Five of these 6 endpoints are real now — "report-summary", "report-wallet-usage",
  // "report-top-spending", "report-cash-flow", and "report-monthly-trend" (each a dedicated
  // aggregation, real `{isSuccess}` envelope below) — because composing them from
  // GET /transactions required too many round trips (one call per wallet, one per month, a
  // whole itemized transaction list just to bucket it client-side, etc). Only
  // "report-category-breakdown" and "export-report" were never built: category breakdown comes
  // bundled inside report-summary's response instead of its own endpoint, and export generation
  // still happens entirely client-side (the "endpoint" is just a filename formatter, no real
  // file is produced server-side). Those two keep the old mock `{success}` envelope on purpose —
  // don't "fix" them to match the real one until they're actually built.
  {
    key: "report",
    titleKey: "apiDoc.groups.report",
    endpoints: [
      {
        id: "report-dashboard-summary",
        title: "Dashboard Summary",
        method: "GET",
        endpoint: "/reports/dashboard-summary?month=2026-07",
        payload: [{ name: "month", type: "string (YYYY-MM)", required: false }],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil ringkasan dashboard",
            isSuccess: true,
            status: 200,
            data: {
              wallet: { totalBalance: 5_400_000, walletCount: 3 },
              investment: { totalCurrentValue: 12_800_000, instrumentCount: 4 },
              monthly: {
                income: 8_000_000,
                expense: 3_250_000,
                savings: 4_750_000,
                investmentInflow: 1_500_000,
              },
              financialHealth: {
                score: 19,
                status: "needsAttention",
                savingRate: 19,
                isCashFlowPositive: true,
                isExpenseStable: true,
              },
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "report-summary",
        title: "Report Summary",
        method: "GET",
        endpoint:
          "/reports/summary?dateFrom=2026-07-01&dateTo=2026-07-31&previousDateFrom=2026-06-01&previousDateTo=2026-06-30",
        payload: [
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
          { name: "previousDateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "previousDateTo", type: "string (YYYY-MM-DD)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil ringkasan laporan",
            isSuccess: true,
            status: 200,
            data: {
              totalIncome: { value: 12_450_000, changePercent: 18 },
              totalExpense: { value: 7_850_000, changePercent: -8 },
              netCashFlow: { value: 4_600_000, changePercent: 32 },
              transactionCount: { value: 84, changePercent: 16 },
              categoryBreakdown: [
                {
                  idCategory: "category-1",
                  nameCategory: "Makanan",
                  color: "#E2574C",
                  icon: "HiOutlineCake",
                  amount: 2_986_000,
                  transactionCount: 24,
                  percentage: 38,
                  subCategoryBreakdown: [
                    {
                      idSubCategory: "subcategory-1",
                      nameSubCategory: "Warteg",
                      icon: "MdOutlineRestaurant",
                      amount: 820_000,
                      transactionCount: 9,
                      percentage: 27,
                    },
                  ],
                },
              ],
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "report-cash-flow",
        title: "Cash Flow",
        method: "GET",
        endpoint: "/reports/cash-flow?dateFrom=2026-07-01&dateTo=2026-07-31&locale=id",
        payload: [
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
          { name: "locale", type: "string (BCP 47, e.g. \"id\"/\"en\"/\"ja\")", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil cash flow",
            isSuccess: true,
            status: 200,
            data: [
              { label: "W1", income: 12_450_000, expense: 3_200_000, isToday: false },
              { label: "W2", income: 0, expense: 4_650_000, isToday: true },
              { label: "W3", income: 0, expense: 0, isToday: false },
              { label: "W4", income: 0, expense: 0, isToday: false },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "report-category-breakdown",
        title: "Category Breakdown",
        method: "GET",
        endpoint: "/reports/category-breakdown?dateFrom=2026-07-01&dateTo=2026-07-31",
        payload: [
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
        ],
        successExample: JSON.stringify(
          {
            success: true,
            data: [
              {
                idCategory: "category-1",
                nameCategory: "Makanan",
                color: "#E2574C",
                icon: "HiOutlineCake",
                total: 2_986_000,
                percentage: 38,
                transactionCount: 24,
                subCategories: [
                  { idSubCategory: "subcategory-1", nameSubCategory: "Warteg", total: 820_000, percentage: 27 },
                ],
              },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            success: false,
            message: "Token tidak valid atau sudah kedaluwarsa",
          },
          null,
          2,
        ),
      },
      {
        id: "report-monthly-trend",
        title: "Monthly Trend",
        method: "GET",
        endpoint: "/reports/monthly-trend?months=12&locale=id",
        payload: [
          { name: "months", type: "number", required: false },
          { name: "locale", type: "string (BCP 47, e.g. \"id\"/\"en\"/\"ja\")", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil tren bulanan",
            isSuccess: true,
            status: 200,
            data: [
              { label: "Agu '25", income: 9_500_000, expense: 6_400_000 },
              { label: "Sep '25", income: 9_500_000, expense: 5_900_000 },
              { label: "Jul", income: 12_450_000, expense: 7_850_000 },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "report-wallet-usage",
        title: "Wallet Usage",
        method: "GET",
        endpoint: "/reports/wallet-usage?dateFrom=2026-07-01&dateTo=2026-07-31",
        payload: [
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil penggunaan dompet",
            isSuccess: true,
            status: 200,
            data: [
              { idWallet: "wallet-1", nameWallet: "Jago", color: "#7CB87C", transactionCount: 40, percentage: 48 },
              { idWallet: "wallet-2", nameWallet: "Cash", color: "#4C6FFF", transactionCount: 18, percentage: 22 },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "report-top-spending",
        title: "Top Spending",
        method: "GET",
        endpoint: "/reports/top-spending?dateFrom=2026-07-01&dateTo=2026-07-31&limit=10",
        payload: [
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
          { name: "limit", type: "number", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil pengeluaran terbesar",
            isSuccess: true,
            status: 200,
            data: [
              {
                idTransaction: "transaction-1",
                rank: 1,
                title: "Warteg",
                categoryName: "Makanan",
                subCategoryName: "Warteg",
                amount: 850_000,
                date: "2026-07-12T09:00:00.000Z",
              },
            ],
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            isSuccess: false,
            status: 401,
            data: { error: "Token tidak valid atau sudah kedaluwarsa" },
          },
          null,
          2,
        ),
      },
      {
        id: "export-report",
        title: "Export Report",
        method: "POST",
        endpoint: "/reports/export",
        payload: [
          { name: "format", type: '"pdf" | "excel" | "csv"', required: true },
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
        ],
        successExample: JSON.stringify(
          {
            success: true,
            message: "Laporan berhasil diekspor",
            data: {
              fileName: "laporan_2026-07-01_2026-07-31.pdf",
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            success: false,
            message: "Format export tidak valid",
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "account",
    titleKey: "apiDoc.groups.account",
    endpoints: [
      {
        id: "reset-account-data",
        title: "Reset Account Data",
        method: "DELETE",
        endpoint: "/account/data",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Semua data berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Unauthorized",
            data: {},
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "clientError",
    titleKey: "apiDoc.groups.clientError",
    endpoints: [
      {
        id: "report-client-error",
        title: "Report Client Error",
        method: "POST",
        endpoint: "/errors",
        payload: [
          { name: "source", type: '"render" | "window.onerror" | "unhandledrejection"', required: true },
          { name: "environment", type: '"development" | "production"', required: true },
          { name: "message", type: "string", required: true },
          { name: "stack", type: "string", required: false },
          { name: "path", type: "string", required: false },
          { name: "userAgent", type: "string", required: false },
          { name: "extra", type: "object", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Error berhasil dicatat",
            data: {
              idClientError: "6a5c1a2f9e1d4c0012ab34cd",
              idUser: "6a54775fb2c4f567c96e74f4",
              source: "render",
              environment: "development",
              message: "Cannot read properties of undefined (reading 'map')",
              path: "/dashboard",
              isRead: false,
              createdAt: "2026-07-17T03:12:44.000Z",
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "source, environment, dan message wajib diisi",
            data: { error: "source, environment, dan message wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "list-client-errors",
        title: "List Client Errors",
        method: "GET",
        endpoint: "/errors?search=&environment=&source=",
        payload: [
          { name: "search", type: "string", required: false },
          { name: "environment", type: '"development" | "production"', required: false },
          { name: "source", type: "string", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar error",
            data: [
              {
                idClientError: "6a5c1a2f9e1d4c0012ab34cd",
                idUser: "6a54775fb2c4f567c96e74f4",
                username: "riantosm",
                source: "render",
                environment: "development",
                message: "Cannot read properties of undefined (reading 'map')",
                stack: "Error: Cannot read properties of undefined (reading 'map')\n    at DashboardPage ...",
                path: "/dashboard",
                userAgent: "Mozilla/5.0 ...",
                isRead: false,
                createdAt: "2026-07-17T03:12:44.000Z",
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Forbidden: admin only",
            data: {},
            isSuccess: false,
            status: 403,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-client-error",
        title: "Delete Client Error",
        method: "DELETE",
        endpoint: "/errors/:idClientError",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Error berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Error tidak ditemukan",
            data: { error: "Error tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "settings",
    titleKey: "apiDoc.groups.settings",
    endpoints: [
      {
        id: "get-settings",
        title: "Get Settings",
        method: "GET",
        endpoint: "/settings",
        payload: [],
        successExample: JSON.stringify(
          {
            success: true,
            data: {
              currency: "IDR",
              decimalPlaces: 0,
              language: "id",
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            success: false,
            message: "Token tidak valid atau sudah kedaluwarsa",
          },
          null,
          2,
        ),
      },
      {
        id: "update-settings",
        title: "Update Settings",
        method: "PATCH",
        endpoint: "/settings",
        payload: [
          { name: "currency", type: '"IDR" | "USD" | "JPY"', required: false },
          { name: "decimalPlaces", type: "0 | 1 | 2", required: false },
          { name: "language", type: '"id" | "en" | "jp"', required: false },
        ],
        successExample: JSON.stringify(
          {
            success: true,
            message: "Pengaturan berhasil diperbarui",
            data: {
              currency: "USD",
              decimalPlaces: 2,
              language: "en",
            },
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            success: false,
            message: "Mata uang tidak valid",
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "investment",
    titleKey: "apiDoc.groups.investment",
    endpoints: [
      {
        id: "get-instruments",
        title: "Get Instruments",
        method: "GET",
        endpoint: "/instruments",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar instrumen investasi",
            data: [
              {
                idInstrument: "6a54775fb2c4f567c96e7501",
                nameInstrument: "Reksadana",
                color: "#7CB87C",
                investmentAccounts: [
                  {
                    idInvestmentAccount: "6a54775fb2c4f567c96e7502",
                    idInstrument: "6a54775fb2c4f567c96e7501",
                    nameInvestmentAccount: "Bibit",
                    investedAmount: 5000000,
                    currentValue: 5250000,
                    isDeleted: false,
                  },
                ],
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          { message: "Unauthorized", data: {}, isSuccess: false, status: 401 },
          null,
          2,
        ),
      },
      {
        id: "create-instrument",
        title: "Create Instrument",
        method: "POST",
        endpoint: "/instruments",
        payload: [
          { name: "nameInstrument", type: "string", required: true },
          { name: "color", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Instrumen investasi berhasil dibuat",
            data: {
              idInstrument: "6a54775fb2c4f567c96e7503",
              nameInstrument: "Emas",
              color: "#F0A343",
              investmentAccounts: [],
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "nameInstrument dan color wajib diisi",
            data: { error: "nameInstrument dan color wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-instrument",
        title: "Update Instrument",
        method: "PATCH",
        endpoint: "/instruments/:idInstrument",
        payload: [
          { name: "nameInstrument", type: "string", required: true },
          { name: "color", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Instrumen investasi berhasil diperbarui",
            data: {
              idInstrument: "6a54775fb2c4f567c96e7503",
              nameInstrument: "Emas Batangan",
              color: "#F0A343",
              investmentAccounts: [],
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Instrumen tidak ditemukan",
            data: { error: "Instrumen tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-instrument",
        title: "Delete Instrument",
        method: "DELETE",
        endpoint: "/instruments/:idInstrument",
        payload: [],
        successExample: JSON.stringify(
          { message: "Instrumen investasi berhasil dihapus", data: {}, isSuccess: true, status: 200 },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Instrumen tidak ditemukan",
            data: { error: "Instrumen tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "create-investment-account",
        title: "Create Investment Account",
        method: "POST",
        endpoint: "/instruments/:idInstrument/accounts",
        payload: [{ name: "nameInvestmentAccount", type: "string", required: true }],
        successExample: JSON.stringify(
          {
            message: "Akun investasi berhasil dibuat",
            data: {
              idInvestmentAccount: "6a54775fb2c4f567c96e7504",
              idInstrument: "6a54775fb2c4f567c96e7501",
              nameInvestmentAccount: "Bibit Adel",
              investedAmount: 0,
              currentValue: 0,
              isDeleted: false,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Instrumen tidak ditemukan",
            data: { error: "Instrumen tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-investment-account",
        title: "Update Investment Account",
        method: "PATCH",
        endpoint: "/instruments/:idInstrument/accounts/:idInvestmentAccount",
        payload: [{ name: "nameInvestmentAccount", type: "string", required: true }],
        successExample: JSON.stringify(
          {
            message: "Akun investasi berhasil diperbarui",
            data: {
              idInvestmentAccount: "6a54775fb2c4f567c96e7504",
              idInstrument: "6a54775fb2c4f567c96e7501",
              nameInvestmentAccount: "Bibit Adel",
              investedAmount: 9000000,
              currentValue: 9500000,
              isDeleted: false,
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Akun investasi tidak ditemukan",
            data: { error: "Akun investasi tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-investment-account",
        title: "Delete Investment Account",
        method: "DELETE",
        endpoint: "/instruments/:idInstrument/accounts/:idInvestmentAccount",
        payload: [],
        successExample: JSON.stringify(
          { message: "Akun investasi berhasil dihapus", data: {}, isSuccess: true, status: 200 },
          null,
          2,
        ),
        // Soft-deletes (isDeleted: true) rather than actually removing the
        // subdocument, so any existing investment-transaction ledger entry
        // can keep resolving this account's name (shown with a "(Deleted)"
        // suffix). Blocked entirely while currentValue is non-zero — the
        // funds must be moved to another account first.
        errorExample: JSON.stringify(
          {
            message:
              "Akun ini masih memiliki nilai saat ini — pindahkan dana ke akun lain terlebih dahulu sebelum menghapus",
            data: {
              error:
                "Akun ini masih memiliki nilai saat ini — pindahkan dana ke akun lain terlebih dahulu sebelum menghapus",
            },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "investmentTransaction",
    titleKey: "apiDoc.groups.investmentTransaction",
    endpoints: [
      {
        id: "get-investment-transactions",
        title: "List Investment Transactions",
        method: "GET",
        endpoint:
          "/investment-transactions?idInstrument=6a54775fb2c4f567c96e7501&idInvestmentAccount=6a54775fb2c4f567c96e7502&type=out&dateFrom=2026-04-01&dateTo=2026-07-15&search=bibit&sort=dateDesc&page=1&limit=20",
        payload: [
          {
            name: "idInstrument",
            type: "string (matches idInstrument OR idInstrumentTo)",
            required: false,
          },
          {
            name: "idInvestmentAccount",
            type: "string (matches idInvestmentAccount OR idInvestmentAccountTo)",
            required: false,
          },
          { name: "type", type: '"in" | "out" | "transfer" | "pl"', required: false },
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: false },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: false },
          {
            name: "search",
            type: "string (matches note, or resolved instrument/account name)",
            required: false,
          },
          {
            name: "sort",
            type: '"dateDesc" | "dateAsc" | "amountDesc" | "amountAsc"',
            required: false,
          },
          { name: "page", type: "number (omit with limit for the full unpaginated result)", required: false },
          { name: "limit", type: "number", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar transaksi investasi",
            data: {
              investmentTransactions: [
                {
                  idInvestmentTransaction: "6a54775fb2c4f567c96e7601",
                  type: "in",
                  date: "2026-07-01T02:00:00.000Z",
                  idInstrument: "6a54775fb2c4f567c96e7501",
                  idInvestmentAccount: "6a54775fb2c4f567c96e7502",
                  idInstrumentTo: null,
                  idInvestmentAccountTo: null,
                  amount: 25000000,
                  investedDelta: 25000000,
                  currentDelta: 25000000,
                  idTransaction: "6a54775fb2c4f567c96e7010",
                },
              ],
              total: 1,
              page: 1,
              limit: 20,
              totalPages: 1,
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          { message: "Unauthorized", data: {}, isSuccess: false, status: 401 },
          null,
          2,
        ),
      },
      {
        id: "get-net-worth-timeline",
        title: "Get Net Worth Timeline",
        method: "GET",
        endpoint:
          "/investment-transactions/net-worth-timeline?granularity=month&dateFrom=2026-04-15&dateTo=2026-07-15&locale=id&idInstrument=6a54775fb2c4f567c96e7501",
        payload: [
          { name: "granularity", type: '"day" | "month" | "year"', required: true },
          { name: "dateFrom", type: "string (YYYY-MM-DD)", required: true },
          { name: "dateTo", type: "string (YYYY-MM-DD)", required: true },
          { name: "locale", type: "string, e.g. \"id\"", required: false },
          {
            name: "idInstrument",
            type: "string, comma-separated ids (e.g. \"a,b\") — omit for the whole portfolio",
            required: false,
          },
        ],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil grafik nilai investasi",
            data: [
              { label: "Apr 2026", date: "2026-04-30T23:59:59.999Z", invested: 5000000, current: 5000000 },
              { label: "Mei 2026", date: "2026-05-31T23:59:59.999Z", invested: 8000000, current: 8250000 },
              { label: "Jun 2026", date: "2026-06-30T23:59:59.999Z", invested: 8000000, current: 8620000 },
              { label: "Jul 2026", date: "2026-07-15T23:59:59.999Z", invested: 8000000, current: 8920248 },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "granularity, dateFrom, dan dateTo wajib diisi",
            data: { error: "granularity, dateFrom, dan dateTo wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "get-investment-timelines",
        title: "Get Investment Timelines",
        method: "GET",
        endpoint: "/investment-transactions/timelines",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil grafik histori investasi",
            data: {
              accounts: {
                "6a54775fb2c4f567c96e7502": [
                  { date: "2026-07-01T02:00:00.000Z", invested: 25000000, current: 25000000 },
                  { date: "2026-07-10T02:00:00.000Z", invested: 25000000, current: 25620000 },
                ],
              },
              instruments: {
                "6a54775fb2c4f567c96e7501": [
                  { date: "2026-07-01T02:00:00.000Z", invested: 25000000, current: 25000000 },
                  { date: "2026-07-10T02:00:00.000Z", invested: 25000000, current: 25620000 },
                ],
              },
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          { message: "Unauthorized", data: {}, isSuccess: false, status: 401 },
          null,
          2,
        ),
      },
      {
        id: "create-money-in",
        title: "Create Money In",
        method: "POST",
        endpoint: "/investment-transactions/in",
        payload: [
          { name: "idInstrument", type: "string", required: true },
          { name: "idInvestmentAccount", type: "string", required: true },
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string", required: true },
          { name: "idTransaction", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Uang masuk investasi berhasil dicatat",
            data: {
              idInvestmentTransaction: "6a54775fb2c4f567c96e7601",
              type: "in",
              date: "2026-07-01T02:00:00.000Z",
              idInstrument: "6a54775fb2c4f567c96e7501",
              idInvestmentAccount: "6a54775fb2c4f567c96e7502",
              idInstrumentTo: null,
              idInvestmentAccountTo: null,
              amount: 25000000,
              investedDelta: 25000000,
              currentDelta: 25000000,
              idTransaction: "6a54775fb2c4f567c96e7010",
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Akun investasi tidak ditemukan",
            data: { error: "Akun investasi tidak ditemukan" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "create-money-out",
        title: "Create Money Out",
        method: "POST",
        endpoint: "/investment-transactions/out",
        payload: [
          { name: "idInstrument", type: "string", required: true },
          { name: "idInvestmentAccount", type: "string", required: true },
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string", required: true },
          { name: "idTransaction", type: "string", required: false },
          { name: "note", type: "string", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Uang keluar investasi berhasil dicatat",
            data: {
              idInvestmentTransaction: "6a54775fb2c4f567c96e7602",
              type: "out",
              date: "2026-07-05T02:00:00.000Z",
              idInstrument: "6a54775fb2c4f567c96e7501",
              idInvestmentAccount: "6a54775fb2c4f567c96e7502",
              idInstrumentTo: null,
              idInvestmentAccountTo: null,
              amount: 5000000,
              investedDelta: -5000000,
              currentDelta: -5000000,
              idTransaction: null,
              note: "Penarikan untuk kebutuhan mendesak",
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Jumlah penarikan melebihi saldo akun",
            data: { error: "Jumlah penarikan melebihi saldo akun" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "create-transfer",
        title: "Create Transfer",
        method: "POST",
        endpoint: "/investment-transactions/transfer",
        payload: [
          { name: "idInstrument", type: "string", required: true },
          { name: "idInvestmentAccount", type: "string", required: true },
          { name: "idInstrumentTo", type: "string", required: true },
          { name: "idInvestmentAccountTo", type: "string", required: true },
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Transfer investasi berhasil dicatat",
            data: {
              idInvestmentTransaction: "6a54775fb2c4f567c96e7603",
              type: "transfer",
              date: "2026-07-06T02:00:00.000Z",
              idInstrument: "6a54775fb2c4f567c96e7501",
              idInvestmentAccount: "6a54775fb2c4f567c96e7502",
              idInstrumentTo: "6a54775fb2c4f567c96e7503",
              idInvestmentAccountTo: "6a54775fb2c4f567c96e7504",
              amount: 2000000,
              investedDelta: -2000000,
              currentDelta: -2000000,
              idTransaction: null,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Jumlah transfer melebihi saldo akun sumber",
            data: { error: "Jumlah transfer melebihi saldo akun sumber" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "create-profit-loss",
        title: "Create Profit/Loss",
        method: "POST",
        endpoint: "/investment-transactions/pl",
        payload: [
          { name: "idInstrument", type: "string", required: true },
          { name: "idInvestmentAccount", type: "string", required: true },
          { name: "newCurrentValue", type: "number", required: true },
          { name: "date", type: "string", required: true },
        ],
        successExample: JSON.stringify(
          {
            message: "Perubahan nilai investasi berhasil dicatat",
            data: {
              idInvestmentTransaction: "6a54775fb2c4f567c96e7604",
              type: "pl",
              date: "2026-07-07T02:00:00.000Z",
              idInstrument: "6a54775fb2c4f567c96e7501",
              idInvestmentAccount: "6a54775fb2c4f567c96e7502",
              idInstrumentTo: null,
              idInvestmentAccountTo: null,
              amount: 2000,
              investedDelta: 0,
              currentDelta: 2000,
              idTransaction: null,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Nilai saat ini tidak berubah",
            data: { error: "Nilai saat ini tidak berubah" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-investment-transaction",
        title: "Update Investment Transaction",
        method: "PATCH",
        endpoint: "/investment-transactions/:idInvestmentTransaction",
        payload: [
          { name: "amount", type: "number", required: true },
          { name: "date", type: "string", required: true },
          { name: "note", type: "string", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Transaksi investasi berhasil diperbarui",
            data: {
              idInvestmentTransaction: "6a54775fb2c4f567c96e7602",
              type: "out",
              date: "2026-07-05T02:00:00.000Z",
              idInstrument: "6a54775fb2c4f567c96e7501",
              idInvestmentAccount: "6a54775fb2c4f567c96e7502",
              idInstrumentTo: null,
              idInvestmentAccountTo: null,
              amount: 5000000,
              investedDelta: -5000000,
              currentDelta: -5000000,
              idTransaction: null,
              note: "Penarikan untuk kebutuhan mendesak - updated",
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Tidak bisa diperbarui, transaksi lain setelahnya bergantung pada perubahan ini",
            data: {
              error: "Tidak bisa diperbarui, transaksi lain setelahnya bergantung pada perubahan ini",
            },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-investment-transaction",
        title: "Delete Investment Transaction",
        method: "DELETE",
        endpoint: "/investment-transactions/:idInvestmentTransaction",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Transaksi investasi berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Tidak bisa menghapus, transaksi lain setelahnya bergantung pada perubahan ini",
            data: {
              error: "Tidak bisa menghapus, transaksi lain setelahnya bergantung pada perubahan ini",
            },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
  {
    key: "budget",
    titleKey: "apiDoc.groups.budget",
    endpoints: [
      {
        id: "get-budgets",
        title: "List Budgets",
        method: "GET",
        endpoint: "/budgets",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Berhasil mengambil daftar anggaran",
            data: [
              {
                idBudget: "6a705f1a7b76529dd52a2301",
                name: "Monthly Spending",
                color: "#4A90E2",
                idCategories: [],
                limitAmount: 4000000,
                childLimits: [
                  {
                    idCategory: "6a705cfb7b76529dd52a2099",
                    idSubCategory: null,
                    limitAmount: 300000,
                  },
                ],
                isPinned: true,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Token tidak valid atau sudah kedaluwarsa",
            data: {},
            isSuccess: false,
            status: 401,
          },
          null,
          2,
        ),
      },
      {
        id: "create-budget",
        title: "Create Budget",
        method: "POST",
        endpoint: "/budgets",
        payload: [
          { name: "name", type: "string", required: true },
          { name: "color", type: "string (hex)", required: true },
          {
            name: "idCategories",
            type: "string[] (empty = every expense category)",
            required: true,
          },
          { name: "limitAmount", type: "number", required: true },
          { name: "isPinned", type: "boolean", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Anggaran berhasil dibuat",
            data: {
              idBudget: "6a705f1a7b76529dd52a2302",
              name: "Makan",
              color: "#4F9E94",
              idCategories: ["6a705cfb7b76529dd52a2099"],
              limitAmount: 1000000,
              childLimits: [],
              isPinned: false,
            },
            isSuccess: true,
            status: 201,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "name, color, dan limitAmount wajib diisi",
            data: {},
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "update-budget",
        title: "Update Budget",
        method: "PATCH",
        endpoint: "/budgets/:idBudget",
        payload: [
          { name: "name", type: "string", required: false },
          { name: "color", type: "string (hex)", required: false },
          {
            name: "idCategories",
            type: "string[] (empty = every expense category)",
            required: false,
          },
          { name: "limitAmount", type: "number", required: false },
          {
            name: "childLimits",
            type: "BudgetChildLimit[] (full replacement array)",
            required: false,
          },
          { name: "isPinned", type: "boolean", required: false },
        ],
        successExample: JSON.stringify(
          {
            message: "Anggaran berhasil diperbarui",
            data: {
              idBudget: "6a705f1a7b76529dd52a2302",
              name: "Makan",
              color: "#4F9E94",
              idCategories: ["6a705cfb7b76529dd52a2099"],
              limitAmount: 1200000,
              childLimits: [
                {
                  idCategory: "6a705cfb7b76529dd52a2099",
                  idSubCategory: "6a705e6b7b76529dd52a2257",
                  limitAmount: 300000,
                },
              ],
              isPinned: true,
            },
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Anggaran tidak ditemukan",
            data: {},
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "delete-budget",
        title: "Delete Budget",
        method: "DELETE",
        endpoint: "/budgets/:idBudget",
        payload: [],
        successExample: JSON.stringify(
          {
            message: "Anggaran berhasil dihapus",
            data: {},
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "Anggaran tidak ditemukan",
            data: {},
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
      {
        id: "reorder-budgets",
        title: "Reorder Budgets",
        method: "PATCH",
        endpoint: "/budgets/reorder",
        payload: [{ name: "orderedIds", type: "string[]", required: true }],
        successExample: JSON.stringify(
          {
            message: "Urutan anggaran berhasil disimpan",
            data: [
              {
                idBudget: "6a705f1a7b76529dd52a2302",
                name: "Makan",
                color: "#4F9E94",
                idCategories: ["6a705cfb7b76529dd52a2099"],
                limitAmount: 1000000,
                childLimits: [],
                isPinned: false,
              },
              {
                idBudget: "6a705f1a7b76529dd52a2301",
                name: "Monthly Spending",
                color: "#4A90E2",
                idCategories: [],
                limitAmount: 4000000,
                childLimits: [
                  {
                    idCategory: "6a705cfb7b76529dd52a2099",
                    idSubCategory: null,
                    limitAmount: 300000,
                  },
                ],
                isPinned: true,
              },
            ],
            isSuccess: true,
            status: 200,
          },
          null,
          2,
        ),
        errorExample: JSON.stringify(
          {
            message: "orderedIds wajib diisi",
            data: { error: "orderedIds wajib diisi" },
            isSuccess: false,
            status: 400,
          },
          null,
          2,
        ),
      },
    ],
  },
];
