import type { IconType } from "react-icons";
import {
  LuApple,
  LuArchive,
  LuBadgePercent,
  LuBanknote,
  LuBike,
  LuBriefcase,
  LuBuilding2,
  LuBus,
  LuCamera,
  LuCar,
  LuCarTaxiFront,
  LuChartColumn,
  LuChartPie,
  LuCircleDollarSign,
  LuCircleDot,
  LuCircleHelp,
  LuCirclePlay,
  LuClapperboard,
  LuClipboardList,
  LuCoffee,
  LuCoins,
  LuCreditCard,
  LuCroissant,
  LuDroplets,
  LuFileText,
  LuFlag,
  LuFlame,
  LuFlower2,
  LuFolder,
  LuFuel,
  LuGamepad2,
  LuGem,
  LuGift,
  LuHandCoins,
  LuHandHeart,
  LuHospital,
  LuHouse,
  LuIceCreamCone,
  LuJoystick,
  LuLandmark,
  LuLeaf,
  LuMap,
  LuMapPin,
  LuMonitorSmartphone,
  LuMusic,
  LuPawPrint,
  LuPhone,
  LuPizza,
  LuPuzzle,
  LuQrCode,
  LuReceiptText,
  LuRepeat,
  LuRocket,
  LuSandwich,
  LuShirt,
  LuShoppingBag,
  LuShoppingCart,
  LuSignal,
  LuSmile,
  LuSofa,
  LuStar,
  LuTag,
  LuThumbsUp,
  LuTicket,
  LuTrainFront,
  LuTrendingUp,
  LuTrophy,
  LuTruck,
  LuUsers,
  LuUtensils,
  LuUtensilsCrossed,
  LuVideo,
  LuWallet,
  LuWalletCards,
  LuWatch,
  LuWifi,
  LuWind,
  LuWrench,
  LuZap,
} from "react-icons/lu";

// Stored icon names (`name`) are persisted in the backend and must never change —
// they keep their original react-icons identifiers; only the rendered glyph maps
// to the Lucide set used by the Mist design.
export interface CategoryIconOption {
  name: string;
  icon: IconType;
  labelKey: string;
}

export interface CategoryIconGroup {
  key: string;
  titleKey: string;
  icons: CategoryIconOption[];
}

export const CATEGORY_ICON_GROUPS: CategoryIconGroup[] = [
  {
    key: "general",
    titleKey: "category.iconGroups.general",
    icons: [
      { name: "HiOutlineTag", icon: LuTag, labelKey: "tag" },
      { name: "HiOutlineStar", icon: LuStar, labelKey: "star" },
      { name: "HiOutlineFolder", icon: LuFolder, labelKey: "folder" },
      { name: "HiOutlineArchiveBox", icon: LuArchive, labelKey: "archive" },
      {
        name: "HiOutlineClipboardDocumentList",
        icon: LuClipboardList,
        labelKey: "checklist",
      },
      { name: "HiOutlineFlag", icon: LuFlag, labelKey: "flag" },
      { name: "HiOutlineQuestionMarkCircle", icon: LuCircleHelp, labelKey: "other" },
      { name: "HiOutlineDocumentText", icon: LuFileText, labelKey: "document" },
    ],
  },
  {
    key: "food",
    titleKey: "category.iconGroups.food",
    icons: [
      { name: "IoFastFoodOutline", icon: LuSandwich, labelKey: "food" },
      { name: "MdOutlineRestaurant", icon: LuUtensilsCrossed, labelKey: "restaurant" },
      { name: "MdOutlineFlatware", icon: LuUtensils, labelKey: "cutlery" },
      { name: "MdOutlineLocalCafe", icon: LuCoffee, labelKey: "cafe" },
      { name: "MdOutlineBakeryDining", icon: LuCroissant, labelKey: "bakery" },
      { name: "MdOutlineLocalPizza", icon: LuPizza, labelKey: "pizza" },
      { name: "MdOutlineIcecream", icon: LuIceCreamCone, labelKey: "dessert" },
      { name: "HiOutlineFire", icon: LuFlame, labelKey: "cooking" },
      { name: "MdOutlineEco", icon: LuLeaf, labelKey: "vegetable" },
      { name: "MdOutlineLocalGroceryStore", icon: LuApple, labelKey: "produce" },
    ],
  },
  {
    key: "dailyNeeds",
    titleKey: "category.iconGroups.dailyNeeds",
    icons: [
      { name: "MdOutlineCheckroom", icon: LuShirt, labelKey: "clothing" },
      { name: "HiOutlineWifi", icon: LuWifi, labelKey: "internet" },
      { name: "HiOutlineShoppingCart", icon: LuShoppingCart, labelKey: "groceries" },
      { name: "HiOutlineShoppingBag", icon: LuShoppingBag, labelKey: "shoppingBag" },
      { name: "MdOutlineWatch", icon: LuWatch, labelKey: "accessories" },
      { name: "MdOutlineDiamond", icon: LuGem, labelKey: "jewelry" },
      { name: "HiOutlineHome", icon: LuHouse, labelKey: "home" },
      { name: "HiOutlineHomeModern", icon: LuSofa, labelKey: "household" },
      { name: "HiOutlineBolt", icon: LuZap, labelKey: "electricity" },
      { name: "HiOutlinePhone", icon: LuPhone, labelKey: "phoneBill" },
      { name: "HiOutlineWrenchScrewdriver", icon: LuWrench, labelKey: "repair" },
      { name: "HiOutlineReceiptPercent", icon: LuBadgePercent, labelKey: "discount" },
      { name: "HiOutlineTicket", icon: LuTicket, labelKey: "voucher" },
      { name: "HiOutlineGiftTop", icon: LuGift, labelKey: "giftBox" },
      { name: "MdOutlineDevices", icon: LuMonitorSmartphone, labelKey: "electronics" },
      { name: "MdOutlineSimCard", icon: LuSignal, labelKey: "mobileData" },
    ],
  },
  {
    key: "transport",
    titleKey: "category.iconGroups.transport",
    icons: [
      { name: "MdOutlineDirectionsCar", icon: LuCar, labelKey: "car" },
      { name: "MdOutlineTwoWheeler", icon: LuBike, labelKey: "motorcycle" },
      { name: "MdOutlineDirectionsBus", icon: LuBus, labelKey: "bus" },
      { name: "MdOutlineLocalGasStation", icon: LuFuel, labelKey: "fuel" },
      { name: "MdOutlineLocalTaxi", icon: LuCarTaxiFront, labelKey: "taxi" },
      { name: "HiOutlineMapPin", icon: LuMapPin, labelKey: "location" },
      { name: "HiOutlineMap", icon: LuMap, labelKey: "route" },
      { name: "HiOutlineTruck", icon: LuTruck, labelKey: "delivery" },
      { name: "MdOutlineTrain", icon: LuTrainFront, labelKey: "train" },
      { name: "MdOutlineLocalCarWash", icon: LuDroplets, labelKey: "carWash" },
    ],
  },
  {
    key: "hobby",
    titleKey: "category.iconGroups.hobby",
    icons: [
      { name: "MdOutlineSportsEsports", icon: LuGamepad2, labelKey: "esports" },
      { name: "MdOutlineVideogameAsset", icon: LuJoystick, labelKey: "gameTopup" },
      { name: "HiOutlinePuzzlePiece", icon: LuPuzzle, labelKey: "games" },
      { name: "HiOutlineMusicalNote", icon: LuMusic, labelKey: "music" },
      { name: "HiOutlineFilm", icon: LuClapperboard, labelKey: "movie" },
      { name: "HiOutlineCamera", icon: LuCamera, labelKey: "photography" },
      { name: "HiOutlineTrophy", icon: LuTrophy, labelKey: "sports" },
      { name: "HiOutlinePlayCircle", icon: LuCirclePlay, labelKey: "streaming" },
      { name: "HiOutlineVideoCamera", icon: LuVideo, labelKey: "video" },
      { name: "MdOutlinePool", icon: LuCircleDot, labelKey: "billiard" },
      { name: "MdOutlineVapingRooms", icon: LuWind, labelKey: "vape" },
    ],
  },
  {
    key: "paymentOther",
    titleKey: "category.iconGroups.paymentOther",
    icons: [
      { name: "HiOutlineCreditCard", icon: LuCreditCard, labelKey: "creditCard" },
      { name: "MdOutlineCreditScore", icon: LuWalletCards, labelKey: "debitCard" },
      { name: "HiOutlineBanknotes", icon: LuBanknote, labelKey: "cash" },
      { name: "HiOutlineQrCode", icon: LuQrCode, labelKey: "digitalPayment" },
      { name: "HiOutlineWallet", icon: LuWallet, labelKey: "wallet" },
      { name: "HiOutlineBuildingLibrary", icon: LuLandmark, labelKey: "bank" },
      { name: "HiOutlineReceiptRefund", icon: LuReceiptText, labelKey: "refund" },
      { name: "MdOutlinePayments", icon: LuHandCoins, labelKey: "payment" },
      { name: "MdOutlineSubscriptions", icon: LuRepeat, labelKey: "subscription" },
    ],
  },
  {
    key: "investment",
    titleKey: "category.iconGroups.investment",
    icons: [
      { name: "HiOutlineChartPie", icon: LuChartPie, labelKey: "investment" },
      { name: "HiOutlineChartBar", icon: LuChartColumn, labelKey: "chart" },
      { name: "HiOutlineArrowTrendingUp", icon: LuTrendingUp, labelKey: "profit" },
      { name: "HiOutlineCurrencyDollar", icon: LuCircleDollarSign, labelKey: "money" },
      { name: "HiOutlineBriefcase", icon: LuBriefcase, labelKey: "job" },
      { name: "HiOutlineRocketLaunch", icon: LuRocket, labelKey: "business" },
      { name: "HiOutlineHandThumbUp", icon: LuThumbsUp, labelKey: "bonus" },
      { name: "MdOutlineCurrencyExchange", icon: LuCoins, labelKey: "exchange" },
      { name: "HiOutlineBuildingOffice", icon: LuBuilding2, labelKey: "office" },
    ],
  },
  {
    key: "health",
    titleKey: "category.iconGroups.health",
    icons: [
      { name: "MdOutlineLocalHospital", icon: LuHospital, labelKey: "health" },
      { name: "MdOutlineSpa", icon: LuFlower2, labelKey: "spa" },
      { name: "MdOutlineFace", icon: LuSmile, labelKey: "skincare" },
      { name: "MdOutlinePets", icon: LuPawPrint, labelKey: "pet" },
    ],
  },
  {
    key: "social",
    titleKey: "category.iconGroups.social",
    icons: [
      { name: "HiOutlineUserGroup", icon: LuUsers, labelKey: "social" },
      { name: "MdOutlineVolunteerActivism", icon: LuHandHeart, labelKey: "donation" },
    ],
  },
];

export const CATEGORY_ICONS: CategoryIconOption[] = CATEGORY_ICON_GROUPS.flatMap(
  (group) => group.icons,
);

export function resolveCategoryIcon(name: string): IconType {
  return CATEGORY_ICONS.find((option) => option.name === name)?.icon ?? LuTag;
}
