import type { Transaction } from "@/types/transaction.types";

/**
 * Dates are generated relative to "today" (instead of hardcoded) so the demo
 * dataset always spans "3 months ago" through "this month" regardless of when
 * the app is run. Hour is kept within 9-20 local time to avoid the UTC
 * conversion in `toISOString()` shifting the calendar day.
 */
function relativeDate(monthsAgo: number, day: number, hour = 12): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() - monthsAgo;
  const daysInTargetMonth = new Date(year, month + 1, 0).getDate();
  const clampedDay = Math.min(day, daysInTargetMonth);
  return new Date(year, month, clampedDay, hour, 0, 0, 0).toISOString();
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  // 3 months ago
  {
    idTransaction: "txn-1",
    type: "income",
    idWallet: "wallet-2",
    idCategory: "category-gaji",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Gaji Bulanan",
    notes: "",
    amount: 8_000_000,
    date: relativeDate(3, 1, 9),
  },
  {
    idTransaction: "txn-2",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-restoran",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Siang",
    notes: "",
    amount: 75_000,
    date: relativeDate(3, 3, 12),
  },
  {
    idTransaction: "txn-3",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-transportasi",
    idSubCategory: "sub-bensin",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Isi Bensin",
    notes: "",
    amount: 50_000,
    date: relativeDate(3, 5, 17),
  },
  {
    idTransaction: "txn-4",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Belanja Bulanan",
    notes: "",
    amount: 300_000,
    date: relativeDate(3, 10, 19),
  },
  {
    idTransaction: "txn-5",
    type: "transfer",
    idWallet: null,
    idCategory: null,
    idSubCategory: null,
    idWalletFrom: "wallet-2",
    idWalletTo: "wallet-3",
    title: "BCA Transfer Keluar → Gopay Transfer Masuk",
    notes: "",
    amount: 500_000,
    date: relativeDate(3, 15, 10),
  },

  // 2 months ago
  {
    idTransaction: "txn-6",
    type: "income",
    idWallet: "wallet-2",
    idCategory: "category-gaji",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Gaji Bulanan",
    notes: "",
    amount: 8_000_000,
    date: relativeDate(2, 1, 9),
  },
  {
    idTransaction: "txn-7",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-makan",
    idSubCategory: "sub-kopi",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Kopi Pagi",
    notes: "",
    amount: 45_000,
    date: relativeDate(2, 4, 8),
  },
  {
    idTransaction: "txn-8",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-hobi",
    idSubCategory: "sub-topup",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Top Up Mobile Legends",
    notes: "",
    amount: 150_000,
    date: relativeDate(2, 8, 20),
  },
  {
    idTransaction: "txn-9",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Keluarga",
    notes: "",
    amount: 120_000,
    date: relativeDate(2, 12, 19),
  },
  {
    idTransaction: "txn-10",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-transportasi",
    idSubCategory: "sub-ojek",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Ojek ke Kantor",
    notes: "",
    amount: 35_000,
    date: relativeDate(2, 18, 8),
  },

  // 1 month ago
  {
    idTransaction: "txn-11",
    type: "income",
    idWallet: "wallet-2",
    idCategory: "category-gaji",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Gaji Bulanan",
    notes: "",
    amount: 8_000_000,
    date: relativeDate(1, 1, 9),
  },
  {
    idTransaction: "txn-12",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: "sub-internet",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Tagihan Internet",
    notes: "",
    amount: 350_000,
    date: relativeDate(1, 5, 10),
  },
  {
    idTransaction: "txn-13",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-restoran",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Malam",
    notes: "",
    amount: 95_000,
    date: relativeDate(1, 9, 19),
  },
  {
    idTransaction: "txn-14",
    type: "correction",
    idWallet: "wallet-1",
    idCategory: null,
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Koreksi Saldo",
    notes: "",
    amount: 20_000,
    date: relativeDate(1, 20, 15),
  },
  {
    idTransaction: "txn-15",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-transportasi",
    idSubCategory: "sub-bensin",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Isi Bensin",
    notes: "",
    amount: 60_000,
    date: relativeDate(1, 25, 17),
  },

  // this month
  {
    idTransaction: "txn-16",
    type: "income",
    idWallet: "wallet-2",
    idCategory: "category-gaji",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Gaji Bulanan",
    notes: "",
    amount: 8_000_000,
    date: relativeDate(0, 1, 9),
  },
  {
    idTransaction: "txn-17",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-restoran",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Siang",
    notes: "",
    amount: 65_000,
    date: relativeDate(0, 3, 12),
  },
  {
    idTransaction: "txn-18",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Belanja Bulanan",
    notes: "",
    amount: 180_000,
    date: relativeDate(0, 5, 18),
  },
  {
    idTransaction: "txn-19",
    type: "transfer",
    idWallet: null,
    idCategory: null,
    idSubCategory: null,
    idWalletFrom: "wallet-3",
    idWalletTo: "wallet-1",
    title: "Gopay Transfer Keluar → Cash Transfer Masuk",
    notes: "",
    amount: 200_000,
    date: relativeDate(0, 7, 11),
  },
  {
    idTransaction: "txn-20",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-hobi",
    idSubCategory: "sub-topup",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Top Up Mobile Legends",
    notes: "",
    amount: 100_000,
    date: relativeDate(0, 9, 20),
  },
  {
    idTransaction: "txn-21",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-kopi",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Kopi Pagi",
    notes: "",
    amount: 28_000,
    date: relativeDate(0, 11, 8),
  },

  // this month — bigger-ticket purchases, pushes this month's expense total to IDR 10.000.000
  {
    idTransaction: "txn-22",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Cicilan Laptop",
    notes: "",
    amount: 3_000_000,
    date: relativeDate(0, 2, 10),
  },
  {
    idTransaction: "txn-23",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-transportasi",
    idSubCategory: "sub-bensin",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Isi Bensin",
    notes: "",
    amount: 50_000,
    date: relativeDate(0, 2, 15),
  },
  {
    idTransaction: "txn-24",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: "sub-internet",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Tagihan Internet & TV",
    notes: "",
    amount: 400_000,
    date: relativeDate(0, 4, 9),
  },
  {
    idTransaction: "txn-25",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-restoran",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Malam Keluarga",
    notes: "",
    amount: 85_000,
    date: relativeDate(0, 4, 19),
  },
  {
    idTransaction: "txn-26",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-hobi",
    idSubCategory: "sub-topup",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Top Up Valorant Points",
    notes: "",
    amount: 150_000,
    date: relativeDate(0, 6, 11),
  },
  {
    idTransaction: "txn-27",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-hobi",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Beli Headset Gaming",
    notes: "",
    amount: 850_000,
    date: relativeDate(0, 6, 20),
  },
  {
    idTransaction: "txn-28",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-transportasi",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Beli Ban Motor",
    notes: "",
    amount: 700_000,
    date: relativeDate(0, 7, 14),
  },
  {
    idTransaction: "txn-29",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Beli Peralatan Dapur",
    notes: "",
    amount: 650_000,
    date: relativeDate(0, 8, 13),
  },
  {
    idTransaction: "txn-30",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-transportasi",
    idSubCategory: "sub-ojek",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Ojek ke Mall",
    notes: "",
    amount: 45_000,
    date: relativeDate(0, 8, 18),
  },
  {
    idTransaction: "txn-31",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-makan",
    idSubCategory: "sub-restoran",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Makan Malam Kantor",
    notes: "",
    amount: 180_000,
    date: relativeDate(0, 9, 17),
  },
  {
    idTransaction: "txn-32",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Perpanjang STNK",
    notes: "",
    amount: 600_000,
    date: relativeDate(0, 10, 19),
  },
  {
    idTransaction: "txn-33",
    type: "expense",
    idWallet: "wallet-1",
    idCategory: "category-makan",
    idSubCategory: "sub-kopi",
    idWalletFrom: null,
    idWalletTo: null,
    title: "Ngopi Bareng Teman",
    notes: "",
    amount: 32_000,
    date: relativeDate(0, 10, 9),
  },
  {
    idTransaction: "txn-34",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Beli Smartwatch",
    notes: "",
    amount: 2_497_000,
    date: relativeDate(0, 11, 13),
  },
  {
    idTransaction: "txn-35",
    type: "expense",
    idWallet: "wallet-2",
    idCategory: "category-kebutuhan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Service Kulkas",
    notes: "",
    amount: 350_000,
    date: relativeDate(0, 12, 10),
  },
  {
    idTransaction: "txn-36",
    type: "expense",
    idWallet: "wallet-3",
    idCategory: "category-makan",
    idSubCategory: null,
    idWalletFrom: null,
    idWalletTo: null,
    title: "Jajan Sore",
    notes: "",
    amount: 38_000,
    date: relativeDate(0, 12, 16),
  },
];
