export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  TRANSACTIONS: "/transactions",
  WALLET: "/wallet",
  CATEGORIES: "/categories",
  INVESTMENT: "/investment",
  REPORTS: "/reports",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  SETTINGS_API_DOC: "/settings/api-doc",
  SETTINGS_CURRENCY: "/settings/currency",
  SETTINGS_USER_APPROVAL: "/settings/user-approval",
  SETTINGS_ERROR_LOG: "/settings/error-log",
} as const;
